### ISSUE TITLE
有没有人遇到跟我一样的问题,偶发,连续进行同样的操作30次左右会出现一次,已经确定是在主线程刷新的java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification

### ISSUE THREAD

**Issue by AndroidDevo** [huxq17/XRefreshView#102]
从网上查了  都是千篇一律的说adapter没有notifyDataSetChanged()  但是确实已经notifyDataSetChanged()了 ,望大神带带我

java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131755599, class android.widget.ListView) with Adapter()]
                                                                    at android.widget.ListView.layoutChildren(ListView.java:1566)
                                                                    at android.widget.AbsListView.onLayout(AbsListView.java:2161)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at com.andview.refreshview.XRefreshView.onLayout(XRefreshView.java:351)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                    at android.view.View.layout(View.java:15728)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5050)
                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2113)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1867)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6037)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:575)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                	at java.lang.refl

**Comment by huxq17** [comment]
才开始做android吧，这个问题是因为你adapter里用的datalist和子线程里用的是同一个，解决方法就是子线程和adapter里都new list,别用同一个。

**Comment by AndroidDevo** [comment]
补充一下 是直接调用startRefresh()  方法会出现
