### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by zouxianbincc** [huxq17/XRefreshView#18]
上拉加载更多。1,不满一屏，无需加载更多。2.上拉加载更多时，如果加载失败，footerview 不消失，提示方案“加载失败，请点击重新”。3,如果数据满一屏，数据已经加载全部。footerview不消失，方案“已经加载完全部”，每次滑到底部都有这个"已经加载完全部"的footerview。

**Comment by zouxianbincc** [comment]
我是忠实的粉丝。使用这个项目已经快一年了。有什么问题，有什么需求。都是直接找作者。他都是第一时间非常热心的帮忙解决。

**Comment by huxq17** [comment]
第一个调用setpullloadenable(false)或者setloadcomplete(true)都可以达到效果

**Comment by huxq17** [comment]
但是两个方法的效果不一样，可以比较下看看哪个效果是自己需要的

**Comment by huxq17** [comment]
第三个问题
//如果想在数据加载完成以后不隐藏footerview则需要调用下面这行代码并传入false
//        xRefreshView.setHideFooterWhenComplete(false);

第一第二个问题我和你说过解决方案，这里就不写了。

**Comment by shiyuankao** [comment]
数据不足一屏时，调用 setloadcomplete(true) 方法会报空指针错误

**Comment by huxq17** [comment]
不会啊，你用的什么版本，报的什么错

**Comment by shiyuankao** [comment]
`java.lang.NullPointerException
                                                              at com.andview.refreshview.utils.Utils.isRecyclerViewFullscreen(Utils.java:59)
                                                              at com.andview.refreshview.XRefreshContentView.addFooterView(XRefreshContentView.java:438)
                                                              at com.andview.refreshview.XRefreshContentView.stopLoading(XRefreshContentView.java:287)
                                                              at com.andview.refreshview.XRefreshView.stopLoadMore(XRefreshView.java:764)
                                                              at com.andview.refreshview.XRefreshView.setLoadComplete(XRefreshView.java:801)
                                                              at com.myyg.ui.fragment.BiddingRecordFragment$4.onSuccess(BiddingRecordFragment.java:196)
                                                              at com.lidroid.xutils.http.HttpHandler.onProgressUpdate(HttpHandler.java:218)
                                                              at com.lidroid.xutils.task.PriorityAsyncTask$InternalHandler.handleMessage(PriorityAsyncTask.java:385)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:136)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5120)
                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
                                                              at dalvik.system.NativeStart.main(Native Method)`

**Comment by shiyuankao** [comment]
我是用2.1.9的版本

**Comment by huxq17** [comment]
@shiyuankao 这问题我之前改过，在最新的版本里面是没有问题的

**Comment by shiyuankao** [comment]
`        url = MessageFormat.format("{0}/{1}/{2}", url, pageIndex, SysConstant.PAGE_SIZE);
        HttpUtils http = new HttpUtils();
        RequestParams params = BaseApplication.getParams();
        http.send(HttpRequest.HttpMethod.GET, url, params, new RequestCallBack<String>() {

            @Override
            public void onSuccess(ResponseInfo<String> responseInfo) {
                MessageResult message = MessageResult.parse(responseInfo.result);
                List<JoinModel> list = new ArrayList<>();
                if (message.getCode() == SysStatusCode.SUCCESS) {
                    list = JSON.parseArray(message.getData(), JoinModel.class);
                    listJoin.addAll(list);
                    adapter.notifyDataSetChanged();
                }
                //xRefreshView.setLoadComplete(true);
                if (list.size() < SysConstant.PAGE_SIZE) {
                    xRefreshView.setLoadComplete(true);
                }else{
                   xRefreshView.stopLoadMore();
                }
            }

            @Override
            public void onFailure(HttpException e, String s) {
                xRefreshView.stopLoadMore();
            }
        });`

**Comment by shiyuankao** [comment]
这是我的代码，是不是代码上有问题的

**Comment by shiyuankao** [comment]
我更新到最新版本上试试

**Comment by huxq17** [comment]
你换成3.0.0的版本

**Comment by shiyuankao** [comment]
更新到最新版本可以了
