### ISSUE TITLE
刷新recyclerview列表数据由不满屏到满屏出现crash

### ISSUE THREAD

**Issue by 1181631922** [huxq17/XRefreshView#32]
如题，crash信息为：
`java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                    at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5177)
                                                                    at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:5248)
                                                                    at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7678)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3333)
                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                    at android.view.View.layout(View.java:16630)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                    at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                    at com.grape.wine.view.xrefreshview.XRefreshView.onLayout(XRefreshView.java:268)`

**Comment by huxq17** [comment]
你用的是什么版本的？

**Comment by 1181631922** [comment]
3.1

**Comment by huxq17** [comment]
概率有多大，你有时间的话做个有问题的demo给我看看吧

**Comment by 1181631922** [comment]
百分百，在项目里，拿不出来

**Comment by 1181631922** [comment]
我给你个gif图吧，你可以模拟一下，这样应该可以吧？

**Comment by huxq17** [comment]
是这样的，这个问题我遇到过并解决掉了，不清楚是那个版本了，你换成最新的版本看下还有没有问题。没有的话就算了，还有的话就再说

**Comment by 1181631922** [comment]
恩，我把版本升级一下试试

**Comment by huxq17** [comment]
还有问题么？

**Comment by 1181631922** [comment]
好了，搞定了，谢谢

**Comment by quyuan2744** [comment]
怎么搞定的?

**Comment by huxq17** [comment]
用最新版本。@quyuan2744

**Comment by quyuan2744** [comment]
什么的最新版本,我用的com.jcodecraeer:xrecyclerview:1.2.7

**Comment by huxq17** [comment]
兄弟，你跑偏了。

**Comment by quyuan2744** [comment]
啊?什么意思啊?

**Comment by huxq17** [comment]
这个项目是XRefreshView，不是xrecyclerview

**Comment by quyuan2744** [comment]
我用的应该是谁写的框架吧  不太知道 前期不是我弄的

**Comment by huxq17** [comment]
你把你使用的代码贴出来看看

**Comment by quyuan2744** [comment]
在项目里,抽取不出来呀,我应该去更新什么东西啊?>
