### ISSUE TITLE
上拉和下拉同时进行会奔溃。

### ISSUE THREAD

**Issue by ww3mm4** [huxq17/XRefreshView#55]

**Comment by huxq17** [comment]
具体什么情况，能详细点么？

**Comment by huxq17** [comment]
报的什么错误，有log么

**Comment by ww3mm4** [comment]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{f310fb2 position=1 id=-1, oldPos=1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                                       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5220)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5402)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3457)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3252)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at com.andview.refreshview.XRefreshView.onLayout(XRefreshView.java:352)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java)
                                                                       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java)
                                                                       at android.view.View.layout(View.java)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
                                                                       at android.os.Handler.handleCallback(Handler.java)
                                                                       at android.os.Handler.dispatchMessage(Handler.java)
                                                                       at android.os.Looper.loop(Looper.java)
                                                                   	at android.app.ActivityThread.main(Acti
02-04 09:18:49.273 25400-25854/system_process E/ActivityManager: Invalid thumbnail dimensions: 0x0

**Comment by ww3mm4** [comment]
上拉加载，和下拉刷新同时进行，就这样

**Comment by ww3mm4** [comment]
at com.andview.refreshview.XRefreshView.onLayout(XRefreshView.java:352)
这一行错误，但是我比较笨看不懂。。。

**Comment by huxq17** [comment]
写个有问题的demo发给我看看吧

**Comment by lumleon** [comment]
請問找到解決方法沒有？

**Comment by TMLAndroid** [comment]
应该是刷新的时候清除了数据，上拉加载更多的时候会加载数据，然后上拉加载更多插入的数据插入数据发现数据为空才会出现这种异常
