### ISSUE TITLE
下拉刷新，说我list越界了。  没有报我自己代码问题.下面贴了报错日志

### ISSUE THREAD

**Issue by xiapQu** [huxq17/XRefreshView#71]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{34a7ecdc position=0 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent}
                                                                  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5249)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5431)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3486)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3262)
                                                                  at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1633)
                                                                  at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:341)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5280)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by huxq17** [comment]
写个有问题的demo发给我看看吧
